"""Role family ontology — career tracks with capability and intensity metadata."""

from __future__ import annotations

from career_intelligence_engine.models.ontology import RoleFamilyDefinition, RoleFamilyId

# Phase 2 semantic enrichment overlay for calibrated ontology-driven scoring
_SEMANTIC_OVERLAY: dict[RoleFamilyId, dict] = {
    RoleFamilyId.PROGRAM_LEADERSHIP: {
        "positive_signals": [
            "program governance", "portfolio management", "benefits realization",
            "executive sponsor", "cross-functional", "stakeholder management",
            "pmo", "program director", "initiative portfolio",
            "portfolio governance", "steering committee", "budgeting",
            "executive program review", "multi-program orchestration",
        ],
        "negative_signals": [
            "coded", "unit testing", "pull request", "recruiting",
            "quota attainment", "financial modeling",
        ],
        "executive_signals": [
            "steering committee", "executive reporting", "portfolio governance",
            "benefits tracking", "executive sponsor", "governance board",
        ],
        "far_families": [RoleFamilyId.HR, RoleFamilyId.SALES, RoleFamilyId.FINANCE],
        "archetype_keywords": ["portfolio leader", "program executive", "pmo director"],
        "governance_weight": 0.85,
        "delivery_weight": 0.70,
        "strategy_weight": 0.65,
        "execution_weight": 0.55,
        "transformation_weight": 0.50,
    },
    RoleFamilyId.TECHNICAL_PROGRAM_MANAGEMENT: {
        "positive_signals": [
            "technical program", "dependency management", "release train",
            "engineering roadmap", "architecture alignment", "architecture coordination",
            "technical dependency management", "engineering coordination",
            "integration delivery", "platform delivery", "sdlc",
            "cross-team coordination", "devops coordination", "azure delivery",
        ],
        "negative_signals": [
            "product roadmap", "user research", "prd", "quota",
            "employee relations", "financial modeling",
        ],
        "executive_signals": [
            "engineering program governance", "release governance",
            "architecture review board", "technical steering",
        ],
        "far_families": [RoleFamilyId.HR, RoleFamilyId.SALES, RoleFamilyId.FINANCE],
        "archetype_keywords": ["technical program leader", "engineering delivery lead"],
        "governance_weight": 0.55,
        "delivery_weight": 0.85,
        "strategy_weight": 0.40,
        "execution_weight": 0.80,
        "transformation_weight": 0.35,
    },
    RoleFamilyId.AI_PROGRAM_MANAGEMENT: {
        "positive_signals": [
            "ai program", "use case portfolio", "pilot to production",
            "model lifecycle", "ai roadmap", "mlops", "genai initiative",
        ],
        "negative_signals": [
            "ios development", "frontend", "recruiting", "sales pipeline",
        ],
        "executive_signals": [
            "ai center of excellence", "ai governance council",
            "responsible ai framework", "ai strategy steering",
        ],
        "far_families": [RoleFamilyId.HR, RoleFamilyId.SALES, RoleFamilyId.FINANCE],
        "archetype_keywords": ["ai program lead", "ml initiative owner"],
        "governance_weight": 0.60,
        "delivery_weight": 0.75,
        "strategy_weight": 0.55,
        "execution_weight": 0.65,
        "transformation_weight": 0.85,
    },
    RoleFamilyId.AI_TRANSFORMATION: {
        "positive_signals": [
            "ai strategy", "ai transformation", "genai", "responsible ai",
            "model governance", "mlops", "use case portfolio",
            "enterprise ai", "ai operating model",
        ],
        "negative_signals": [
            "unit testing", "code review", "recruiting", "quota",
            "fp&a", "compensation analysis",
        ],
        "executive_signals": [
            "ai strategy ownership", "ai governance board", "steering committee",
            "enterprise transformation", "operating model", "executive sponsor",
        ],
        "far_families": [
            RoleFamilyId.HR, RoleFamilyId.SALES, RoleFamilyId.FINANCE,
            RoleFamilyId.SOFTWARE_ENGINEERING,
        ],
        "archetype_keywords": ["ai transformation leader", "head of ai", "chief ai officer"],
        "governance_weight": 0.75,
        "delivery_weight": 0.55,
        "strategy_weight": 0.90,
        "execution_weight": 0.45,
        "transformation_weight": 0.95,
    },
    RoleFamilyId.ENTERPRISE_DELIVERY: {
        "positive_signals": [
            "global rollout", "enterprise rollout", "erp implementation", "crm implementation",
            "change management", "si partner", "multi-geography",
            "client delivery", "implementation lead", "delivery governance",
            "operational execution", "delivery assurance", "enterprise-scale implementation",
        ],
        "negative_signals": [
            "product-market fit", "user research", "recruiting",
            "software engineer", "quota attainment",
        ],
        "executive_signals": [
            "client executive sponsor", "delivery governance",
            "program steering", "benefits realization",
        ],
        "far_families": [RoleFamilyId.HR, RoleFamilyId.SALES, RoleFamilyId.PRODUCT_MANAGEMENT],
        "archetype_keywords": ["delivery lead", "engagement manager", "implementation director"],
        "governance_weight": 0.50,
        "delivery_weight": 0.90,
        "strategy_weight": 0.35,
        "execution_weight": 0.85,
        "transformation_weight": 0.45,
    },
    RoleFamilyId.TRANSFORMATION_OFFICE: {
        "positive_signals": [
            "transformation office", "tmo", "transformation roadmap",
            "value realization", "benefits tracking", "operating model",
            "transformation portfolio",
        ],
        "negative_signals": [
            "unit testing", "recruiting", "sales pipeline", "coding",
        ],
        "executive_signals": [
            "transformation steering", "executive committee",
            "portfolio governance", "benefits realization board",
        ],
        "far_families": [RoleFamilyId.HR, RoleFamilyId.SALES, RoleFamilyId.SOFTWARE_ENGINEERING],
        "archetype_keywords": ["transformation director", "tmo lead", "chief transformation officer"],
        "governance_weight": 0.80,
        "delivery_weight": 0.55,
        "strategy_weight": 0.85,
        "execution_weight": 0.40,
        "transformation_weight": 0.90,
    },
    RoleFamilyId.DIGITAL_TRANSFORMATION: {
        "positive_signals": [
            "digital transformation", "digital strategy", "customer journey",
            "digital operating model", "omnichannel", "digitization",
        ],
        "negative_signals": [
            "recruiting", "quota", "unit testing", "ios developer",
        ],
        "executive_signals": [
            "digital steering committee", "executive sponsor",
            "transformation governance", "operating model redesign",
        ],
        "far_families": [RoleFamilyId.HR, RoleFamilyId.SALES, RoleFamilyId.SOFTWARE_ENGINEERING],
        "archetype_keywords": ["digital transformation lead", "head of digital"],
        "governance_weight": 0.65,
        "delivery_weight": 0.60,
        "strategy_weight": 0.80,
        "execution_weight": 0.50,
        "transformation_weight": 0.85,
    },
    RoleFamilyId.AI_GOVERNANCE: {
        "positive_signals": [
            "ai governance", "responsible ai", "model risk", "model monitoring",
            "bias testing", "ai policy", "regulatory alignment", "ai ethics",
        ],
        "negative_signals": [
            "sales pipeline", "recruiting", "frontend development",
        ],
        "executive_signals": [
            "governance board", "model governance board", "ai ethics council",
            "regulatory steering", "risk committee",
        ],
        "far_families": [RoleFamilyId.SALES, RoleFamilyId.HR],
        "archetype_keywords": ["ai governance lead", "responsible ai manager"],
        "governance_weight": 0.90,
        "delivery_weight": 0.35,
        "strategy_weight": 0.60,
        "execution_weight": 0.30,
        "transformation_weight": 0.65,
    },
    RoleFamilyId.RELEASE_GOVERNANCE: {
        "positive_signals": [
            "release governance", "release train", "release calendar",
            "cutover", "uat", "hypercare", "quality gate", "release management",
            "cab", "deployment governance", "sdlc governance", "production release",
            "release cadence",
        ],
        "negative_signals": [
            "product roadmap", "user research", "recruiting", "sales quota",
        ],
        "executive_signals": [
            "release governance board", "quality gate committee",
        ],
        "far_families": [RoleFamilyId.HR, RoleFamilyId.SALES, RoleFamilyId.FINANCE],
        "archetype_keywords": ["release manager", "release train engineer"],
        "governance_weight": 0.70,
        "delivery_weight": 0.80,
        "strategy_weight": 0.25,
        "execution_weight": 0.85,
        "transformation_weight": 0.30,
    },
    RoleFamilyId.PRODUCT_DELIVERY: {
        "positive_signals": [
            "product launch", "product delivery lead", "product operations",
            "roadmap ownership", "product lifecycle", "go-to-market execution",
        ],
        "negative_signals": [
            "technical program manager", "release train", "sdlc", "dependency management",
            "steering committee", "portfolio governance", "program governance",
            "cross-functional delivery",
        ],
        "executive_signals": ["product council", "launch steering"],
        "far_families": [RoleFamilyId.HR, RoleFamilyId.FINANCE, RoleFamilyId.SOFTWARE_ENGINEERING],
        "archetype_keywords": ["product delivery lead", "product operations"],
        "governance_weight": 0.40,
        "delivery_weight": 0.75,
        "strategy_weight": 0.55,
        "execution_weight": 0.60,
        "transformation_weight": 0.30,
    },
    RoleFamilyId.PRODUCT_MANAGEMENT: {
        "positive_signals": [
            "product roadmap", "prd", "user research", "go-to-market",
            "product-market fit", "product strategy", "feature prioritization",
        ],
        "negative_signals": [
            "program governance", "portfolio governance", "steering committee",
            "erp implementation", "pmo director", "technical program manager",
            "release train", "sdlc",
        ],
        "executive_signals": [
            "product council", "product strategy review",
        ],
        "far_families": [RoleFamilyId.HR, RoleFamilyId.FINANCE, RoleFamilyId.TRANSFORMATION_OFFICE],
        "archetype_keywords": ["product manager", "product owner", "head of product"],
        "governance_weight": 0.35,
        "delivery_weight": 0.55,
        "strategy_weight": 0.75,
        "execution_weight": 0.50,
        "transformation_weight": 0.35,
    },
    RoleFamilyId.OPERATIONS: {
        "positive_signals": [
            "run operations", "operational continuity", "sla management",
            "incident management", "production support", "service operations",
            "operational cadence", "noc",
        ],
        "negative_signals": [
            "technical program", "release train", "program governance",
            "steering committee", "ai strategy", "portfolio governance",
            "operating model redesign",
        ],
        "executive_signals": ["operations steering", "operating committee"],
        "far_families": [
            RoleFamilyId.SOFTWARE_ENGINEERING,
            RoleFamilyId.AI_TRANSFORMATION,
            RoleFamilyId.TECHNICAL_PROGRAM_MANAGEMENT,
        ],
        "archetype_keywords": ["operations manager", "it operations"],
        "governance_weight": 0.45,
        "delivery_weight": 0.50,
        "strategy_weight": 0.25,
        "execution_weight": 0.70,
        "transformation_weight": 0.20,
    },
    RoleFamilyId.ENTERPRISE_OPERATIONS: {
        "positive_signals": [
            "enterprise operations", "run operations", "sla management",
            "incident management", "operational continuity", "service level",
        ],
        "negative_signals": [
            "software engineer", "unit testing", "ai strategy", "model governance",
            "technical program manager", "release train", "program governance",
        ],
        "executive_signals": [
            "operations steering", "executive reporting", "operating committee",
        ],
        "far_families": [RoleFamilyId.SOFTWARE_ENGINEERING, RoleFamilyId.AI_TRANSFORMATION],
        "archetype_keywords": ["operations director", "bizops lead"],
        "governance_weight": 0.55,
        "delivery_weight": 0.70,
        "strategy_weight": 0.40,
        "execution_weight": 0.75,
        "transformation_weight": 0.35,
    },
    RoleFamilyId.SOFTWARE_ENGINEERING: {
        "positive_signals": [
            "software engineer", "microservices", "kubernetes", "code review",
            "system design", "unit testing", "ci/cd", "api development",
        ],
        "negative_signals": [
            "steering committee", "portfolio governance", "benefits realization",
            "executive sponsor", "transformation office", "program governance",
        ],
        "executive_signals": [],
        "far_families": [
            RoleFamilyId.HR, RoleFamilyId.SALES, RoleFamilyId.FINANCE,
            RoleFamilyId.AI_TRANSFORMATION, RoleFamilyId.TRANSFORMATION_OFFICE,
            RoleFamilyId.PROGRAM_LEADERSHIP,
        ],
        "archetype_keywords": ["software engineer", "developer", "sre", "ios developer"],
        "governance_weight": 0.10,
        "delivery_weight": 0.40,
        "strategy_weight": 0.15,
        "execution_weight": 0.95,
        "transformation_weight": 0.20,
    },
    RoleFamilyId.HR: {
        "positive_signals": [
            "employee relations", "compensation", "benefits", "talent acquisition",
            "performance management", "hris", "people operations",
        ],
        "negative_signals": [
            "program governance", "technical program", "ai strategy",
            "release train", "architecture alignment",
        ],
        "executive_signals": ["hr business partner", "people committee"],
        "far_families": [
            RoleFamilyId.AI_TRANSFORMATION, RoleFamilyId.TECHNICAL_PROGRAM_MANAGEMENT,
            RoleFamilyId.PROGRAM_LEADERSHIP, RoleFamilyId.SOFTWARE_ENGINEERING,
        ],
        "archetype_keywords": ["hrbp", "talent acquisition", "people ops"],
        "governance_weight": 0.30,
        "delivery_weight": 0.35,
        "strategy_weight": 0.25,
        "execution_weight": 0.40,
        "transformation_weight": 0.15,
    },
    RoleFamilyId.SALES: {
        "positive_signals": [
            "pipeline", "forecast", "quota attainment", "deal closure",
            "account executive", "crm", "business development",
        ],
        "negative_signals": [
            "program governance", "technical program", "ai transformation",
            "release governance", "steering committee",
        ],
        "executive_signals": ["sales leadership", "quota review"],
        "far_families": [
            RoleFamilyId.AI_TRANSFORMATION, RoleFamilyId.TECHNICAL_PROGRAM_MANAGEMENT,
            RoleFamilyId.PROGRAM_LEADERSHIP, RoleFamilyId.SOFTWARE_ENGINEERING,
        ],
        "archetype_keywords": ["account executive", "sales manager", "bdr"],
        "governance_weight": 0.15,
        "delivery_weight": 0.30,
        "strategy_weight": 0.35,
        "execution_weight": 0.55,
        "transformation_weight": 0.10,
    },
    RoleFamilyId.FINANCE: {
        "positive_signals": [
            "financial modeling", "variance analysis", "sox", "budgeting",
            "forecasting", "fp&a", "treasury", "gaap",
        ],
        "negative_signals": [
            "technical program", "ai strategy", "release train",
            "program governance", "steering committee",
        ],
        "executive_signals": ["finance committee", "audit committee"],
        "far_families": [
            RoleFamilyId.AI_TRANSFORMATION, RoleFamilyId.TECHNICAL_PROGRAM_MANAGEMENT,
            RoleFamilyId.PROGRAM_LEADERSHIP, RoleFamilyId.SOFTWARE_ENGINEERING,
        ],
        "archetype_keywords": ["financial analyst", "fp&a", "controller"],
        "governance_weight": 0.40,
        "delivery_weight": 0.25,
        "strategy_weight": 0.45,
        "execution_weight": 0.50,
        "transformation_weight": 0.15,
    },
}


def _apply_semantic_overlay(
    families: dict[RoleFamilyId, RoleFamilyDefinition],
) -> dict[RoleFamilyId, RoleFamilyDefinition]:
    """Merge Phase 2 semantic ontology fields into role family definitions."""
    enriched: dict[RoleFamilyId, RoleFamilyDefinition] = {}
    for fid, defn in families.items():
        overlay = _SEMANTIC_OVERLAY.get(fid, {})
        if overlay:
            enriched[fid] = defn.model_copy(update=overlay)
        else:
            enriched[fid] = defn
    return enriched


_BASE_ROLE_FAMILIES: dict[RoleFamilyId, RoleFamilyDefinition] = {
    RoleFamilyId.PROGRAM_LEADERSHIP: RoleFamilyDefinition(
        id=RoleFamilyId.PROGRAM_LEADERSHIP,
        display_name="Program Leadership",
        canonical_titles=[
            "program director",
            "program manager",
            "senior program manager",
            "portfolio manager",
            "pmo director",
            "head of programs",
        ],
        adjacent_families=[
            RoleFamilyId.TECHNICAL_PROGRAM_MANAGEMENT,
            RoleFamilyId.ENTERPRISE_DELIVERY,
            RoleFamilyId.AI_TRANSFORMATION,
            RoleFamilyId.TRANSFORMATION_OFFICE,
            RoleFamilyId.AI_PROGRAM_MANAGEMENT,
        ],
        excluded_families=[
            RoleFamilyId.HR,
            RoleFamilyId.SALES,
            RoleFamilyId.SOFTWARE_ENGINEERING,
        ],
        seniority_patterns=[
            r"\bsenior\b",
            r"\bprincipal\b",
            r"\bdirector\b",
            r"\bhead of\b",
            r"\bvp\b",
        ],
        title_signals=["program", "portfolio", "pmo", "initiative"],
        experience_signals=[
            "cross-functional",
            "stakeholder",
            "roadmap",
            "program governance",
            "benefits realization",
            "executive sponsor",
        ],
        skill_signals=["program management", "pmi", "pmp", "agile at scale"],
        primary_capabilities=[
            "enterprise_delivery",
            "program_portfolio_governance",
            "stakeholder_executive_leadership",
        ],
        secondary_capabilities=["agile_at_scale", "change_transformation"],
        leadership_intensity=0.85,
        transformation_intensity=0.5,
        enterprise_depth=0.8,
    ),
    RoleFamilyId.TECHNICAL_PROGRAM_MANAGEMENT: RoleFamilyDefinition(
        id=RoleFamilyId.TECHNICAL_PROGRAM_MANAGEMENT,
        display_name="Technical Program Management",
        canonical_titles=[
            "technical program manager",
            "tpm",
            "senior technical program manager",
            "engineering program manager",
        ],
        adjacent_families=[
            RoleFamilyId.PROGRAM_LEADERSHIP,
            RoleFamilyId.RELEASE_GOVERNANCE,
            RoleFamilyId.ENTERPRISE_DELIVERY,
            RoleFamilyId.AI_PROGRAM_MANAGEMENT,
            RoleFamilyId.PLATFORM_MODERNIZATION,
        ],
        excluded_families=[
            RoleFamilyId.HR,
            RoleFamilyId.SALES,
            RoleFamilyId.FINANCE,
        ],
        seniority_patterns=[r"\bsenior\b", r"\bprincipal\b", r"\bdirector\b"],
        title_signals=["technical program", "tpm", "engineering program"],
        experience_signals=[
            "platform",
            "release train",
            "dependency management",
            "architecture alignment",
            "engineering roadmap",
        ],
        skill_signals=["jira", "confluence", "sdlc", "ci/cd", "api"],
        primary_capabilities=[
            "technical_program_execution",
            "enterprise_delivery",
        ],
        secondary_capabilities=["agile_at_scale", "cloud_infrastructure"],
        leadership_intensity=0.6,
        transformation_intensity=0.35,
        enterprise_depth=0.65,
    ),
    RoleFamilyId.AI_PROGRAM_MANAGEMENT: RoleFamilyDefinition(
        id=RoleFamilyId.AI_PROGRAM_MANAGEMENT,
        display_name="AI Program Management",
        canonical_titles=[
            "ai program manager",
            "ml program manager",
            "genai program manager",
            "ai initiative lead",
        ],
        adjacent_families=[
            RoleFamilyId.AI_TRANSFORMATION,
            RoleFamilyId.PROGRAM_LEADERSHIP,
            RoleFamilyId.TECHNICAL_PROGRAM_MANAGEMENT,
            RoleFamilyId.AI_GOVERNANCE,
        ],
        excluded_families=[RoleFamilyId.HR, RoleFamilyId.SALES, RoleFamilyId.FINANCE],
        seniority_patterns=[r"\bsenior\b", r"\blead\b", r"\bdirector\b"],
        title_signals=["ai program", "ml program", "genai", "ai initiative"],
        experience_signals=[
            "use case portfolio",
            "pilot to production",
            "model lifecycle",
            "ai roadmap",
        ],
        skill_signals=["generative ai", "llm", "rag", "responsible ai", "mlops"],
        primary_capabilities=["ai_transformation", "technical_program_execution"],
        secondary_capabilities=["ai_governance_risk", "enterprise_delivery"],
        leadership_intensity=0.65,
        transformation_intensity=0.85,
        enterprise_depth=0.7,
    ),
    RoleFamilyId.AI_TRANSFORMATION: RoleFamilyDefinition(
        id=RoleFamilyId.AI_TRANSFORMATION,
        display_name="AI Transformation",
        canonical_titles=[
            "ai transformation lead",
            "head of ai",
            "ai transformation director",
            "chief ai officer",
        ],
        adjacent_families=[
            RoleFamilyId.AI_PROGRAM_MANAGEMENT,
            RoleFamilyId.DIGITAL_TRANSFORMATION,
            RoleFamilyId.TRANSFORMATION_OFFICE,
            RoleFamilyId.AI_GOVERNANCE,
        ],
        excluded_families=[
            RoleFamilyId.HR,
            RoleFamilyId.SALES,
            RoleFamilyId.FINANCE,
        ],
        seniority_patterns=[r"\blead\b", r"\bhead\b", r"\bdirector\b"],
        title_signals=["ai transformation", "ai strategy", "genai", "machine learning"],
        experience_signals=[
            "ai strategy",
            "model governance",
            "responsible ai",
            "mlops",
            "pilot to production",
            "use case portfolio",
        ],
        skill_signals=[
            "generative ai",
            "rag",
            "responsible ai",
            "llm",
            "ai governance",
        ],
        primary_capabilities=["ai_transformation", "change_transformation"],
        secondary_capabilities=["ai_governance_risk", "data_analytics_intelligence"],
        leadership_intensity=0.75,
        transformation_intensity=0.95,
        enterprise_depth=0.75,
    ),
    RoleFamilyId.ENTERPRISE_DELIVERY: RoleFamilyDefinition(
        id=RoleFamilyId.ENTERPRISE_DELIVERY,
        display_name="Enterprise Delivery",
        canonical_titles=[
            "delivery manager",
            "engagement manager",
            "enterprise project manager",
            "client delivery lead",
            "transformation delivery lead",
        ],
        adjacent_families=[
            RoleFamilyId.PROGRAM_LEADERSHIP,
            RoleFamilyId.ENTERPRISE_OPERATIONS,
            RoleFamilyId.TECHNICAL_PROGRAM_MANAGEMENT,
            RoleFamilyId.RELEASE_GOVERNANCE,
        ],
        excluded_families=[
            RoleFamilyId.HR,
            RoleFamilyId.SALES,
            RoleFamilyId.SOFTWARE_ENGINEERING,
        ],
        seniority_patterns=[r"\bsenior\b", r"\bdirector\b", r"\bprincipal\b"],
        title_signals=["delivery", "engagement", "implementation", "rollout"],
        experience_signals=[
            "global rollout",
            "erp",
            "crm implementation",
            "change management",
            "si partner",
            "multi-geography",
        ],
        skill_signals=["sap", "salesforce", "servicenow", "workday"],
        primary_capabilities=["enterprise_delivery", "enterprise_platforms"],
        secondary_capabilities=["change_transformation", "release_quality_governance"],
        leadership_intensity=0.55,
        transformation_intensity=0.45,
        enterprise_depth=0.85,
    ),
    RoleFamilyId.TRANSFORMATION_OFFICE: RoleFamilyDefinition(
        id=RoleFamilyId.TRANSFORMATION_OFFICE,
        display_name="Transformation Office",
        canonical_titles=[
            "transformation office lead",
            "transformation director",
            "chief transformation officer",
            "tmo director",
        ],
        adjacent_families=[
            RoleFamilyId.PROGRAM_LEADERSHIP,
            RoleFamilyId.DIGITAL_TRANSFORMATION,
            RoleFamilyId.ENTERPRISE_DELIVERY,
        ],
        excluded_families=[RoleFamilyId.HR, RoleFamilyId.SALES],
        seniority_patterns=[r"\bdirector\b", r"\bvp\b", r"\bhead\b"],
        title_signals=["transformation office", "tmo", "transformation portfolio"],
        experience_signals=[
            "transformation roadmap",
            "value realization",
            "benefits tracking",
            "operating model",
        ],
        skill_signals=["transformation", "change management", "portfolio management"],
        primary_capabilities=["change_transformation", "program_portfolio_governance"],
        secondary_capabilities=["stakeholder_executive_leadership", "enterprise_delivery"],
        leadership_intensity=0.8,
        transformation_intensity=0.9,
        enterprise_depth=0.85,
    ),
    RoleFamilyId.ENTERPRISE_ARCHITECTURE_DELIVERY: RoleFamilyDefinition(
        id=RoleFamilyId.ENTERPRISE_ARCHITECTURE_DELIVERY,
        display_name="Enterprise Architecture Delivery",
        canonical_titles=[
            "enterprise architecture lead",
            "solution delivery architect",
            "architecture program manager",
        ],
        adjacent_families=[
            RoleFamilyId.TECHNICAL_PROGRAM_MANAGEMENT,
            RoleFamilyId.PLATFORM_MODERNIZATION,
            RoleFamilyId.ENTERPRISE_DELIVERY,
        ],
        excluded_families=[RoleFamilyId.HR, RoleFamilyId.SALES],
        seniority_patterns=[r"\bprincipal\b", r"\bdirector\b", r"\barchitect\b"],
        title_signals=["enterprise architecture", "solution architecture", "architecture board"],
        experience_signals=[
            "reference architecture",
            "architecture review board",
            "integration architecture",
        ],
        skill_signals=["togaf", "enterprise architecture", "api", "integration"],
        primary_capabilities=["enterprise_architecture", "technical_program_execution"],
        secondary_capabilities=["enterprise_platforms", "cloud_infrastructure"],
        leadership_intensity=0.55,
        transformation_intensity=0.55,
        enterprise_depth=0.8,
    ),
    RoleFamilyId.PLATFORM_MODERNIZATION: RoleFamilyDefinition(
        id=RoleFamilyId.PLATFORM_MODERNIZATION,
        display_name="Platform Modernization",
        canonical_titles=[
            "platform modernization lead",
            "platform transformation manager",
            "modernization program manager",
        ],
        adjacent_families=[
            RoleFamilyId.CLOUD_TRANSFORMATION,
            RoleFamilyId.TECHNICAL_PROGRAM_MANAGEMENT,
            RoleFamilyId.ENTERPRISE_ARCHITECTURE_DELIVERY,
        ],
        excluded_families=[RoleFamilyId.HR, RoleFamilyId.SALES],
        seniority_patterns=[r"\bsenior\b", r"\bdirector\b"],
        title_signals=["platform modernization", "legacy modernization", "platform migration"],
        experience_signals=[
            "legacy decommission",
            "platform migration",
            "cloud migration",
            "api modernization",
        ],
        skill_signals=["kubernetes", "microservices", "cloud", "api"],
        primary_capabilities=["cloud_infrastructure", "enterprise_platforms"],
        secondary_capabilities=["technical_program_execution", "enterprise_architecture"],
        leadership_intensity=0.5,
        transformation_intensity=0.7,
        enterprise_depth=0.75,
    ),
    RoleFamilyId.RELEASE_GOVERNANCE: RoleFamilyDefinition(
        id=RoleFamilyId.RELEASE_GOVERNANCE,
        display_name="Release Governance",
        canonical_titles=[
            "release manager",
            "release governance lead",
            "release train engineer",
        ],
        adjacent_families=[
            RoleFamilyId.TECHNICAL_PROGRAM_MANAGEMENT,
            RoleFamilyId.ENTERPRISE_DELIVERY,
        ],
        excluded_families=[RoleFamilyId.HR, RoleFamilyId.SALES, RoleFamilyId.FINANCE],
        seniority_patterns=[r"\bsenior\b", r"\blead\b"],
        title_signals=["release", "release train", "release governance"],
        experience_signals=[
            "release calendar",
            "cutover",
            "uat",
            "hypercare",
            "quality gate",
        ],
        skill_signals=["release management", "ci/cd", "sdlc", "safe"],
        primary_capabilities=["release_quality_governance", "technical_program_execution"],
        secondary_capabilities=["agile_at_scale", "enterprise_delivery"],
        leadership_intensity=0.4,
        transformation_intensity=0.3,
        enterprise_depth=0.6,
    ),
    RoleFamilyId.DIGITAL_TRANSFORMATION: RoleFamilyDefinition(
        id=RoleFamilyId.DIGITAL_TRANSFORMATION,
        display_name="Digital Transformation",
        canonical_titles=[
            "digital transformation lead",
            "digital transformation director",
            "head of digital",
        ],
        adjacent_families=[
            RoleFamilyId.TRANSFORMATION_OFFICE,
            RoleFamilyId.AI_TRANSFORMATION,
            RoleFamilyId.ENTERPRISE_DELIVERY,
        ],
        excluded_families=[RoleFamilyId.HR, RoleFamilyId.SALES],
        seniority_patterns=[r"\bdirector\b", r"\bhead\b", r"\bvp\b"],
        title_signals=["digital transformation", "digital strategy", "digitization"],
        experience_signals=[
            "customer journey",
            "digital operating model",
            "omnichannel",
            "digital roadmap",
        ],
        skill_signals=["transformation", "change management", "cloud", "analytics"],
        primary_capabilities=["change_transformation", "cloud_infrastructure"],
        secondary_capabilities=["product_strategy", "data_analytics_intelligence"],
        leadership_intensity=0.7,
        transformation_intensity=0.85,
        enterprise_depth=0.8,
    ),
    RoleFamilyId.PRODUCT_DELIVERY: RoleFamilyDefinition(
        id=RoleFamilyId.PRODUCT_DELIVERY,
        display_name="Product Delivery",
        canonical_titles=[
            "product delivery lead",
            "product operations manager",
            "director product delivery",
        ],
        adjacent_families=[
            RoleFamilyId.PRODUCT_MANAGEMENT,
            RoleFamilyId.ENTERPRISE_DELIVERY,
            RoleFamilyId.TECHNICAL_PROGRAM_MANAGEMENT,
        ],
        excluded_families=[RoleFamilyId.HR, RoleFamilyId.FINANCE],
        seniority_patterns=[r"\bsenior\b", r"\bdirector\b"],
        title_signals=["product delivery", "product operations", "launch"],
        experience_signals=[
            "product launch",
            "roadmap ownership",
            "product lifecycle",
        ],
        skill_signals=["product roadmap", "go-to-market", "feature prioritization"],
        primary_capabilities=["product_strategy", "enterprise_delivery"],
        secondary_capabilities=["agile_at_scale", "release_quality_governance"],
        leadership_intensity=0.55,
        transformation_intensity=0.4,
        enterprise_depth=0.6,
    ),
    RoleFamilyId.ENTERPRISE_OPERATIONS: RoleFamilyDefinition(
        id=RoleFamilyId.ENTERPRISE_OPERATIONS,
        display_name="Enterprise Operations",
        canonical_titles=[
            "enterprise operations manager",
            "business operations director",
            "global operations lead",
        ],
        adjacent_families=[
            RoleFamilyId.OPERATIONS,
            RoleFamilyId.ENTERPRISE_DELIVERY,
            RoleFamilyId.PROGRAM_LEADERSHIP,
        ],
        excluded_families=[RoleFamilyId.SOFTWARE_ENGINEERING],
        seniority_patterns=[r"\bsenior\b", r"\bdirector\b"],
        title_signals=["enterprise operations", "global operations", "bizops"],
        experience_signals=[
            "operating model",
            "process improvement",
            "vendor management",
            "service level",
        ],
        skill_signals=["okrs", "lean", "six sigma", "sql", "tableau"],
        primary_capabilities=["operations_excellence", "enterprise_delivery"],
        secondary_capabilities=["program_portfolio_governance", "financial_operations"],
        leadership_intensity=0.6,
        transformation_intensity=0.35,
        enterprise_depth=0.75,
    ),
    RoleFamilyId.AI_GOVERNANCE: RoleFamilyDefinition(
        id=RoleFamilyId.AI_GOVERNANCE,
        display_name="AI Governance",
        canonical_titles=[
            "ai governance lead",
            "responsible ai manager",
            "model risk manager",
            "ai ethics lead",
        ],
        adjacent_families=[
            RoleFamilyId.AI_TRANSFORMATION,
            RoleFamilyId.AI_PROGRAM_MANAGEMENT,
            RoleFamilyId.PROGRAM_LEADERSHIP,
        ],
        excluded_families=[RoleFamilyId.SALES, RoleFamilyId.HR],
        seniority_patterns=[r"\blead\b", r"\bdirector\b", r"\bmanager\b"],
        title_signals=["ai governance", "responsible ai", "model risk", "ai ethics"],
        experience_signals=[
            "model monitoring",
            "bias testing",
            "ai policy",
            "regulatory alignment",
        ],
        skill_signals=["responsible ai", "model governance", "ai policy", "compliance"],
        primary_capabilities=["ai_governance_risk", "ai_transformation"],
        secondary_capabilities=["security_compliance", "data_analytics_intelligence"],
        leadership_intensity=0.5,
        transformation_intensity=0.65,
        enterprise_depth=0.7,
    ),
    RoleFamilyId.CLOUD_TRANSFORMATION: RoleFamilyDefinition(
        id=RoleFamilyId.CLOUD_TRANSFORMATION,
        display_name="Cloud Transformation",
        canonical_titles=[
            "cloud transformation lead",
            "cloud program manager",
            "cloud migration director",
        ],
        adjacent_families=[
            RoleFamilyId.PLATFORM_MODERNIZATION,
            RoleFamilyId.TECHNICAL_PROGRAM_MANAGEMENT,
            RoleFamilyId.ENTERPRISE_DELIVERY,
        ],
        excluded_families=[RoleFamilyId.HR, RoleFamilyId.SALES],
        seniority_patterns=[r"\bsenior\b", r"\bdirector\b"],
        title_signals=["cloud transformation", "cloud migration", "cloud program"],
        experience_signals=[
            "landing zone",
            "cloud migration",
            "finops",
            "multi-cloud",
        ],
        skill_signals=["aws", "azure", "gcp", "kubernetes", "terraform"],
        primary_capabilities=["cloud_infrastructure", "enterprise_platforms"],
        secondary_capabilities=["technical_program_execution", "change_transformation"],
        leadership_intensity=0.55,
        transformation_intensity=0.75,
        enterprise_depth=0.7,
    ),
    RoleFamilyId.PRODUCT_MANAGEMENT: RoleFamilyDefinition(
        id=RoleFamilyId.PRODUCT_MANAGEMENT,
        display_name="Product Management",
        canonical_titles=[
            "product manager",
            "senior product manager",
            "group product manager",
            "director of product",
            "head of product",
        ],
        adjacent_families=[
            RoleFamilyId.PRODUCT_DELIVERY,
            RoleFamilyId.SOFTWARE_ENGINEERING,
        ],
        excluded_families=[RoleFamilyId.HR, RoleFamilyId.FINANCE],
        seniority_patterns=[r"\bsenior\b", r"\bgroup\b", r"\bdirector\b"],
        title_signals=["product manager", "product owner", "product lead"],
        experience_signals=[
            "product roadmap",
            "prd",
            "user research",
            "go-to-market",
            "product-market fit",
        ],
        skill_signals=["roadmapping", "a/b testing", "analytics", "figma"],
        primary_capabilities=["product_strategy"],
        secondary_capabilities=["agile_at_scale", "data_analytics_intelligence"],
        leadership_intensity=0.5,
        transformation_intensity=0.35,
        enterprise_depth=0.5,
    ),
    RoleFamilyId.HR: RoleFamilyDefinition(
        id=RoleFamilyId.HR,
        display_name="Human Resources",
        canonical_titles=[
            "hr business partner",
            "hrbp",
            "talent acquisition",
            "people operations",
            "compensation analyst",
        ],
        adjacent_families=[RoleFamilyId.OPERATIONS],
        excluded_families=[
            RoleFamilyId.SOFTWARE_ENGINEERING,
            RoleFamilyId.TECHNICAL_PROGRAM_MANAGEMENT,
            RoleFamilyId.AI_TRANSFORMATION,
        ],
        seniority_patterns=[r"\bpartner\b", r"\bdirector\b", r"\bvp people\b"],
        title_signals=["hr", "human resources", "people", "talent", "recruiting"],
        experience_signals=[
            "employee relations",
            "compensation",
            "benefits",
            "performance management",
            "hris",
        ],
        skill_signals=["workday hcm", "successfactors", "greenhouse", "lever"],
        primary_capabilities=["people_talent"],
        secondary_capabilities=["operations_excellence"],
        leadership_intensity=0.45,
        transformation_intensity=0.15,
        enterprise_depth=0.4,
    ),
    RoleFamilyId.SOFTWARE_ENGINEERING: RoleFamilyDefinition(
        id=RoleFamilyId.SOFTWARE_ENGINEERING,
        display_name="Software Engineering",
        canonical_titles=[
            "software engineer",
            "senior software engineer",
            "staff engineer",
            "engineering manager",
            "ios developer",
            "frontend engineer",
        ],
        adjacent_families=[
            RoleFamilyId.TECHNICAL_PROGRAM_MANAGEMENT,
            RoleFamilyId.PRODUCT_MANAGEMENT,
        ],
        excluded_families=[
            RoleFamilyId.HR,
            RoleFamilyId.SALES,
            RoleFamilyId.FINANCE,
        ],
        seniority_patterns=[r"\bsenior\b", r"\bstaff\b", r"\bprincipal\b"],
        title_signals=[
            "engineer",
            "developer",
            "architect",
            "sre",
            "devops",
            "ios",
            "android",
            "frontend",
            "backend",
        ],
        experience_signals=[
            "microservices",
            "kubernetes",
            "code review",
            "system design",
            "unit testing",
        ],
        skill_signals=[
            "python",
            "java",
            "react",
            "typescript",
            "aws",
            "gcp",
            "kubernetes",
        ],
        primary_capabilities=["software_engineering_craft", "cloud_infrastructure"],
        secondary_capabilities=["technical_program_execution"],
        leadership_intensity=0.35,
        transformation_intensity=0.2,
        enterprise_depth=0.35,
    ),
    RoleFamilyId.SALES: RoleFamilyDefinition(
        id=RoleFamilyId.SALES,
        display_name="Sales",
        canonical_titles=[
            "account executive",
            "sales manager",
            "enterprise sales",
            "business development",
            "solutions consultant",
        ],
        adjacent_families=[RoleFamilyId.OPERATIONS],
        excluded_families=[
            RoleFamilyId.SOFTWARE_ENGINEERING,
            RoleFamilyId.HR,
            RoleFamilyId.TECHNICAL_PROGRAM_MANAGEMENT,
        ],
        seniority_patterns=[r"\benterprise\b", r"\bdirector\b", r"\bvp sales\b"],
        title_signals=["sales", "account executive", "bdr", "sdr", "quota"],
        experience_signals=[
            "pipeline",
            "forecast",
            "quota attainment",
            "deal closure",
            "crm",
        ],
        skill_signals=["salesforce crm", "outreach", "meddic", "challenger sale"],
        primary_capabilities=["sales_gtm"],
        secondary_capabilities=["operations_excellence"],
        leadership_intensity=0.4,
        transformation_intensity=0.1,
        enterprise_depth=0.45,
    ),
    RoleFamilyId.FINANCE: RoleFamilyDefinition(
        id=RoleFamilyId.FINANCE,
        display_name="Finance",
        canonical_titles=[
            "financial analyst",
            "fp&a",
            "controller",
            "finance manager",
            "treasury analyst",
        ],
        adjacent_families=[RoleFamilyId.OPERATIONS],
        excluded_families=[
            RoleFamilyId.SOFTWARE_ENGINEERING,
            RoleFamilyId.AI_TRANSFORMATION,
        ],
        seniority_patterns=[r"\bsenior\b", r"\bdirector\b", r"\bcontroller\b"],
        title_signals=["finance", "fp&a", "accounting", "treasury", "audit"],
        experience_signals=[
            "financial modeling",
            "variance analysis",
            "sox",
            "budgeting",
            "forecasting",
        ],
        skill_signals=["excel", "hyperion", "netsuite", "gaap", "ifrs"],
        primary_capabilities=["financial_operations"],
        secondary_capabilities=["security_compliance"],
        leadership_intensity=0.35,
        transformation_intensity=0.15,
        enterprise_depth=0.5,
    ),
    RoleFamilyId.OPERATIONS: RoleFamilyDefinition(
        id=RoleFamilyId.OPERATIONS,
        display_name="Operations",
        canonical_titles=[
            "operations manager",
            "chief of staff",
            "business operations",
            "strategy and operations",
        ],
        adjacent_families=[
            RoleFamilyId.PROGRAM_LEADERSHIP,
            RoleFamilyId.ENTERPRISE_DELIVERY,
            RoleFamilyId.ENTERPRISE_OPERATIONS,
            RoleFamilyId.FINANCE,
        ],
        excluded_families=[RoleFamilyId.SOFTWARE_ENGINEERING],
        seniority_patterns=[r"\bsenior\b", r"\bdirector\b", r"\bchief of staff\b"],
        title_signals=["operations", "bizops", "chief of staff", "process"],
        experience_signals=[
            "operating model",
            "process improvement",
            "lean",
            "six sigma",
            "vendor management",
        ],
        skill_signals=["sql", "tableau", "process mapping", "okrs"],
        primary_capabilities=["operations_excellence"],
        secondary_capabilities=["program_portfolio_governance", "financial_operations"],
        leadership_intensity=0.5,
        transformation_intensity=0.25,
        enterprise_depth=0.55,
    ),
}


ROLE_FAMILIES: dict[RoleFamilyId, RoleFamilyDefinition] = _apply_semantic_overlay(
    _BASE_ROLE_FAMILIES
)


def get_role_family(family_id: RoleFamilyId) -> RoleFamilyDefinition:
    return ROLE_FAMILIES[family_id]
